###############################################################################
# File         : nor.S
# Project      : EE180 Lab 2: MIPS
#
# Standards/Formatting:
#   MIPS gas, soft tab, 80 column
#
# Description:
#   Test the functionality of the 'nor' instruction.
#
###############################################################################

    .section .boot, "x"
    .balign 4
    .set    noreorder
    .global boot
    .ent    boot
boot:
    lui     $s0, 0x8002         # Load the base address of the status/test registers
    lui     $s2, 0xffff          # Prepare the 'done' status
    nop
    nop
    ori     $s2, $s2, 0xfffe
    nop
    nop
    nor	    $s1, $0, $s2	
    nop
    nop
    sw      $s1, 4($s0)         # Set the test result
    sw      $s1, 0($s0)         # Set 'done'

$done:
    j       $done
    nop

    .end boot